import Head from "next/head";
import { use, useState } from "react";
import { Header } from "~/components/base/header";
import { Sidebar } from "~/components/base/sidebar";
import { useRouter } from "next/router";
import { useUser } from "@clerk/nextjs";
// import Image from "next/image";

// import { api } from "~/utils/api";

export default function BasePage() {
  const { user } = useUser() as {
    user: { imageUrl: string; username: string };
  };
  const [isCollapsed, setIsCollapsed] = useState(false);

  const toggleSidebar = () => setIsCollapsed(!isCollapsed);

  const router = useRouter();
  const { id } = router.query;
  const numericId = Number(id);
  return (
    <>
      <Head>
        <title>Airtable Clone Home Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>
      <main className="flex">
        <div className="flex">
          <div className="fixed w-full border-b border-gray-300 bg-gray-100">
            <Header id={numericId} user={user} />
          </div>
        </div>
        <div className="flex">
          <div className="fixed bg-white" style={{ marginTop: "8.25rem" }}>
            <Sidebar isCollapsed={isCollapsed} toggleSidebar={toggleSidebar} />
          </div>
          <div
            className={`mt-14 transition-all duration-300 ${isCollapsed ? "ml-20" : "ml-80"}`}
          ></div>
        </div>
      </main>
    </>
  );
}
