import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import { api } from "~/utils/api";
import { LoadingPage, LoadingSpinner } from "~/components/loading";

// const CreateBaseWizard = () => {
//   const { user } = useUser();

//   if (!user) {
//     return null;
//   }

//   return (
//     <div className="flex w-auto gap-3">
//       <Image
//         src={user.imageUrl}
//         className="h-9 w-9 rounded-full"
//         alt={`@${user.username}'s profile picture`}
//         width={56}
//         height={56}
//       />
//       <input
//         placeholder="Create a new base"
//         className="grow bg-transparent text-slate-700"
//       />
//     </div>
//   );
// };

const Header = () => {
  const { user } = useUser();

  return (
    <header className="flex items-center justify-between bg-white px-4 py-2 shadow-md">
      {/* Left Section */}
      <div className="flex items-center gap-4">
        {/* Logo */}
        <div className="flex items-center gap-1">
          <Image
            src="/path-to-your-logo.png" // Replace with your logo path
            alt="Logo"
            width={32}
            height={32}
          />
          <span className="text-xl font-semibold text-gray-700">Airtable</span>
        </div>

        {/* Search Bar */}
        <div className="flex items-center rounded-full bg-gray-100 px-3 py-1">
          <input
            type="text"
            placeholder="Search..."
            className="bg-transparent text-gray-600 outline-none"
          />
          <span className="ml-2 text-sm text-gray-400">⌘ K</span>
        </div>
      </div>

      {/* Right Section */}
      <div className="flex items-center gap-4">
        {/* Icons */}
        <button className="rounded-full p-2 hover:bg-gray-100">
          <span className="material-icons">help_outline</span>
        </button>
        <button className="rounded-full p-2 hover:bg-gray-100">
          <span className="material-icons">notifications_none</span>
        </button>

        {/* User Profile */}
        {user && (
          <Image
            src={user.imageUrl}
            className="h-9 w-9 rounded-full"
            alt={`@${user.username}'s profile picture`}
            width={36}
            height={36}
          />
        )}
      </div>
    </header>
  );
};

export default function Home() {
  const user = useUser();
  const { data, isLoading } = api.base.getAll.useQuery();

  if (isLoading || true) {
    return <LoadingPage />;
  }

  if (!data) {
    return <div>Error loading data</div>;
  }

  return (
    <>
      <Head>
        <title>Airtable Clone Home Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>
      <main className="flex h-screen justify-end">
        <div className="w-full border-x border-slate-700 md:max-w-3xl">
          <div className="flex border-b border-slate-700 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />{" "}
              </div>
            )}
            {user.isSignedIn && Header()}
            {/* {user.isSignedIn && (
              <div className="ml-auto flex justify-end p-4">
                <SignOutButton />
              </div>
            )} */}
          </div>
          <div className="flex flex-col">
            {data?.map((base) => (
              <div key={base.id} className="border-b border-slate-700 p-8">
                {base.name}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
