import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const CreateBaseWizard = () => {
  const { user } = useUser();

  console.log(user);
  if (!user) {
    return null;
  }

  return (
    <div className="flex w-auto gap-3">
      <img
        src={user.imageUrl}
        alt="Profile Image"
        className="h-14 w-14 rounded-full"
      />
      <input
        placeholder="Create a new base"
        className="grow bg-transparent text-slate-700"
      />
    </div>
  );
};

export default function Home() {
  const user = useUser();
  const { data, isLoading } = api.base.getAll.useQuery();

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (!data) {
    return <div>Error loading data</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-end">
        <div className="w-full border-x border-slate-700 md:max-w-3xl">
          <div className="flex border-b border-slate-700 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />{" "}
              </div>
            )}
            {user.isSignedIn && CreateBaseWizard()}
            {user.isSignedIn && (
              <div className="ml-auto flex justify-end p-4">
                <SignOutButton />
              </div>
            )}
          </div>
          <div className="flex flex-col">
            {data?.map((base) => (
              <div key={base.id} className="border-b border-slate-700 p-8">
                {base.name}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
