import { useUser, SignInButton } from "@clerk/nextjs";
import Head from "next/head";
import { useState } from "react";
import { Header } from "~/components/home/header";
// import Image from "next/image";

import { api } from "~/utils/api";

export default function BasePage() {
  const { isLoaded: userLoaded, isSignedIn } = useUser();
  const [isCollapsed, setIsCollapsed] = useState(false);

  const toggleSidebar = () => setIsCollapsed(!isCollapsed);
  return (
    <>
      <Head>
        <title>Airtable Clone Home Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>
      <main className="flex">
        {" "}
        <div className="flex flex-row">
          <div className="fixed h-14 w-full border-b border-gray-300 bg-gray-100 p-2">
            {!isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />{" "}
              </div>
            )}
            {isSignedIn && (
              <div>
                <Header
                  isCollapsed={isCollapsed}
                  toggleSidebar={toggleSidebar}
                />
              </div>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
